output   = "appdb"
pkgname  = "appdb"
add-global-variants = true
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "iot"
host   = "localhost"
port   = 5433
user   = "leicom"
pass   = ".test"
schema = "saml_sp"
sslmode = "disable"

[[types]]
[types.match]
type = "null.Int"
nullable = true

[types.replace]
type = "null.Int32"

[[types]]
[types.match]
type = "int"

[types.replace]
type = "int32"
