/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"net/http"
	"strings"
)

// SAML20ApiController binds http requests to an api service and writes the service results to the http response
type SAML20ApiController struct {
	service      SAML20ApiServicer
	errorHandler ErrorHandler
}

// SAML20ApiOption for how the controller is set up.
type SAML20ApiOption func(*SAML20ApiController)

// WithSAML20ApiErrorHandler inject ErrorHandler into controller
func WithSAML20ApiErrorHandler(h ErrorHandler) SAML20ApiOption {
	return func(c *SAML20ApiController) {
		c.errorHandler = h
	}
}

// NewSAML20ApiController creates a default api controller
func NewSAML20ApiController(s SAML20ApiServicer, opts ...SAML20ApiOption) Router {
	controller := &SAML20ApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SAML20ApiController
func (c *SAML20ApiController) Routes() Routes {
	return Routes{
		{
			"SamlAcsPost",
			strings.ToUpper("Post"),
			"/v1/saml/acs",
			c.SamlAcsPost,
		},
		{
			"SamlSloPost",
			strings.ToUpper("Post"),
			"/v1/saml/slo",
			c.SamlSloPost,
		},
	}
}

// SamlAcsPost -
func (c *SAML20ApiController) SamlAcsPost(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.SamlAcsPost(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// SamlSloPost -
func (c *SAML20ApiController) SamlSloPost(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.SamlSloPost(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
