/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// AttributeMap - Maps SAML Attributes to the Eliona User Attributes
type AttributeMap struct {

	// If the attribute mapping is active or not. References to the basic config
	Enable bool `json:"enable,omitempty"`

	// SAML attribute to map to the email (login) of a user
	Email string `json:"email,omitempty"`

	// SAML attribute to map to the first name of a user
	FirstName *string `json:"first_name,omitempty"`

	// SAML attribute to map to the last name of a user
	LastName *string `json:"last_name,omitempty"`

	// SAML attribute to map to the phone number of a user
	Phone *string `json:"phone,omitempty"`
}

// AssertAttributeMapRequired checks if the required fields are not zero-ed
func AssertAttributeMapRequired(obj AttributeMap) error {
	return nil
}

// AssertRecurseAttributeMapRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AttributeMap (e.g. [][]AttributeMap), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAttributeMapRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAttributeMap, ok := obj.(AttributeMap)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAttributeMapRequired(aAttributeMap)
	})
}
