/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// Active - If the service is active
type Active struct {
	Active bool `json:"active,omitempty"`
}

// AssertActiveRequired checks if the required fields are not zero-ed
func AssertActiveRequired(obj Active) error {
	return nil
}

// AssertActiveConstraints checks if the values respects the defined constraints
func AssertActiveConstraints(obj Active) error {
	return nil
}
