/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// RoleMap - Maps eliona user attributes to attribute:values sent in SAML Response
type RoleMap struct {
	ElionaRole string `json:"elionaRole,omitempty"`

	SamlValue string `json:"samlValue,omitempty"`
}

// AssertRoleMapRequired checks if the required fields are not zero-ed
func AssertRoleMapRequired(obj RoleMap) error {
	return nil
}

// AssertRoleMapConstraints checks if the values respects the defined constraints
func AssertRoleMapConstraints(obj RoleMap) error {
	return nil
}
