/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// AdvancedConfiguration - Advanced options to fine tune this SAML Service Provider (SP)
type AdvancedConfiguration struct {

	// If the configuration is enabled or not (connected to the basic config)
	Enable bool `json:"enable,omitempty"`

	// If the configuration is enabled or not
	AllowInitializationByIdp bool `json:"allowInitializationByIdp,omitempty"`

	// If the SP should make a signed SAML Authn-Request or not
	SignedRequest bool `json:"signedRequest,omitempty"`

	// Normaly this value is set to false for a SP. If set to true the user has to re-authenticate (login at IdP) even it has a valid session to the IdP.
	ForceAuthn bool `json:"forceAuthn,omitempty"`

	// If you have to use a customized Entity Id, you can overwrite it here. Normaly the default value can be leave as it is.
	EntityId string `json:"entityId,omitempty"`

	// ff
	CookieSecure *interface{} `json:"cookieSecure,omitempty"`

	// The url to redirect if the login failed. If this value is null the default page /noLogin will showed up
	LoginFailedUrl *interface{} `json:"loginFailedUrl,omitempty"`
}

// AssertAdvancedConfigurationRequired checks if the required fields are not zero-ed
func AssertAdvancedConfigurationRequired(obj AdvancedConfiguration) error {
	return nil
}

// AssertRecurseAdvancedConfigurationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AdvancedConfiguration (e.g. [][]AdvancedConfiguration), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAdvancedConfigurationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAdvancedConfiguration, ok := obj.(AdvancedConfiguration)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAdvancedConfigurationRequired(aAdvancedConfiguration)
	})
}
