/*
 * App SAML 2.0 SSO API
 *
 * API to access and configure the SAML 2.0 SSO service provider
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// AttributeMap - Maps SAML Attributes to the Eliona User Attributes
type AttributeMap struct {

	// Configuration Id refer to config's id. Can only be 1
	Id int32 `json:"id,omitempty"`

	// SAML attribute to map to the email (login) of a user
	Email string `json:"email,omitempty"`

	// SAML attribute to map to the first name of a user
	FirstName *string `json:"firstName,omitempty"`

	// SAML attribute to map to the last name of a user
	LastName *string `json:"lastName,omitempty"`

	// SAML attribute to map to the phone number of a user
	Phone *string `json:"phone,omitempty"`
}

// AssertAttributeMapRequired checks if the required fields are not zero-ed
func AssertAttributeMapRequired(obj AttributeMap) error {
	return nil
}

// AssertAttributeMapConstraints checks if the values respects the defined constraints
func AssertAttributeMapConstraints(obj AttributeMap) error {
	return nil
}
