// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

var TableNames = struct {
	AdvancedConfig string
	AttributeMap   string
	BasicConfig    string
	Permissions    string
}{
	AdvancedConfig: "advanced_config",
	AttributeMap:   "attribute_map",
	BasicConfig:    "basic_config",
	Permissions:    "permissions",
}
